### ISSUE TITLE
Test run_at_sunrise and run_at_sunset

### ISSUE THREAD

**Issue by SvenHoloch** [FlorianKempenich/Appdaemon-Test-Framework#1]
First, great work! Thank you very much!

If I am not wrong, currently it is not possible to write tests for an app that uses the AppDaemon run_at_sunrise() and run_at_sunset() calls.

May it possible to add this feature?

**Comment by FlorianKempenich** [comment]
I'm closing this issue for now. 

Feel free to re-open if you wish to share more details on the use-case to possibly draft an implementation.
