### ISSUE TITLE
Error object has no attribute 'AD' when run_hourly() is used

### ISSUE THREAD

**Issue by matt5mith** [FlorianKempenich/Appdaemon-Test-Framework#19]
One of my apps has the following code:

`class Sonos(hass.Hass):

    def initialize(self):
     self.run_hourly(self.run_hourly_callback, time)`

That last line is breaking one of my tests with the following error:

`self = <sonos.sonos.Sonos object at 0x7f5d82296400>

    def get_now(self):
       return self.AD.get_now()

       AttributeError: 'Sonos' object has no attribute 'AD'`

My script only has one very simple test which runs fine if I comment out the self.run_hourly line in the app.  My test script doesn't reference this in any way,  I presume it's being run because it's within the initialize method in the app.

I am running version 2.5 and AppDaemon 3.0.5.  Any help would be appreciated.

**Comment by matt5mith** [comment]
Just an update on this, if I change run_hourly to run_daily, then I don't get the error.  So the problem is very specific to run_hourly.

**Comment by matt5mith** [comment]
Please ignore.  I can see that this has already been resolved (by adding run_hourly to init_framework.py, which will be in the next release.

**Comment by FlorianKempenich** [comment]
All good then :) 
I'll create a release now so you can test your automations seamlessly ASAP :)

**Comment by FlorianKempenich** [comment]
Done, it'll be available in a couple of minutes under version: `2.5.1`
If you have any problem don't hesitate to open another issue or re-open this one ;)

**Comment by matt5mith** [comment]
> 
> 
> Done, it'll be available in a couple of minutes under version: `2.5.1`
> If you have any problem don't hesitate to open another issue or re-open this one ;)

Works great.  Thank you!
