### ISSUE TITLE
Basic installation/running question

### ISSUE THREAD

**Issue by jreed509** [FlorianKempenich/Appdaemon-Test-Framework#23]
Hi, thanks for all the awesome work on this library!

I'm relatively new to pytest in general and had a question on general setup. Where does pytest need to be installed/run (my local machine, the HASS docker container, the Appdaemon docker container)?

So far whenever, I call `assert_that('my_entity_id')`, and try to run a test, I receive an `appdaemontestframework.assert_that.EitherOrAssertionError` error on the pytest console. 

Here's an example of a simple test I've tried:
```
from apps.front_porch_lights import FrontPorchLights
import pytest
from appdaemontestframework import automation_fixture


@automation_fixture(FrontPorchLights)
def front_porch():
    pass


def test_light_turns_on_at_sunset(given_that, front_porch, assert_that):
    given_that.passed_arg('entities').is_set_to('light.front_porch_sconces')
    given_that.state_of('light.front_porch_sconces').is_set_to("off")
    front_porch.lights_on(None, None)
    assert_that('light.front_porch_sconces').was.turned_on()
```

Thanks in advance for any help in getting up and running!

**Comment by jreed509** [comment]
So I think I've answered the first part of my question on my own - I initially wasn't sure how pytest would actually test my Appdaemon script. I think I've started to wrap my head around how purest works now.

That said, I still haven't been able to get past the `EitherOrAssertionError`. It always seems to get hung up on `turn_on()` calls. Here's a portion the output from debugging a test:
```
...
...

At least ONE of the following exceptions should not have been raised
E           
E           The problem is EITHER:
E           call_service('ANY_DOMAIN/turn_on', {'entity_id': 'light.bathroom_vanity_lights'}) call not found
E           
E           OR
E           turn_on('light.bathroom_vanity_lights') call not found
```

**Comment by jreed509** [comment]
Ok, I managed to figure the issue out on my own - it was an error in my `assert_that()...turn_on()` call. In my automation, I set the light to turn on to a specific `brightness_pct` and then in my assertion, I didn't specify that brightness. 

Closing.

**Comment by FlorianKempenich** [comment]
Hi,

I'm glad you could find the solution 😊
I also believe that more expressive error messages would be very welcome, but I'm the sole maintainer and I don't have too much time to dedicate to this project at the moment.

But either way, kudos for solving your issue 👍🙂

**Comment by snowe2010** [comment]
Sorry to resurrect this, but how _do_ you run the tests? I'm using the VS Code supervisor plugin, is it going to be possible to run the tests from within VS Code? Or do I need to ssh into a container?
