### ISSUE TITLE
Deprecation of `hass_functions`

### ISSUE THREAD

**Issue by FlorianKempenich** [FlorianKempenich/Appdaemon-Test-Framework#28]
# Deprecation of `hass_functions`
Hi everyone,

To prepare for the addition of absolutely amazing features related to time-travel, worked on by @lifeisafractal, we are deprecating the direct use of `hass_functions` in favor of accessing them via `HassMocks`.

**If you have any issues with the deprecation, please comment on this thread 🙂**

## Quick migration guide:
- `hass_functions['listen_event']`  
   Replace with `XXXX`
- `hass_functions['listen_state']`  
   Replace with `XXXX`
- `hass_functions['now_is_between']`  
   Replace with `XXXX`
- `hass_functions['notify']`  
   Replace with `XXXX`
Etc . . . . .

**Comment by mcampbellizo** [comment]
It's been a few months on this one and a few PRs have merged pushing things in this direction. Is now a good time to consider closing out this ticket?

**Comment by lifeisafractal** [comment]
It's been a few months on this one and a few PRs have merged pushing things in this direction. Is now a good time to consider closing out this ticket?

**Comment by FlorianKempenich** [comment]
Oh yes. I think it was an issue that I raised after one of you PR where the migration away from the deprecated function wasn't clear. But in the meantime, if I remember correctly, you implemented a slightly different way and updated the readme. So this issue doesn't make sense anymore :) 
I'm closing
