### ISSUE TITLE
Create a Changelog

### ISSUE THREAD

**Issue by FlorianKempenich** [FlorianKempenich/Appdaemon-Test-Framework#29]
Following a conversation with @lifeisafractal on one of his PR, he recommended we keep a changelog and use proper semantic versioning. I agree it would be a great idea. So here we are 🙂 

This issue is here to track the progress made on the Changelog and to host any discussions related to changelog / semantic versioning.

**Resources**
- Changelog: https://keepachangelog.com/en/1.0.0/
- Semantic Versioning: https://semver.org/

we would like to

**Comment by lifeisafractal** [comment]
Since this has been kicking around for a couple weeks I was going to take a stab at a PR for this. My plan was to reconstruct as much of a change log from old commits as possible and lay out the rest of the info in the PR description (and update the README as well).
