### ISSUE TITLE
Should we be supporting Appdaemon v3 and v4? or only the latest (v4)?

### ISSUE THREAD

**Issue by FlorianKempenich** [FlorianKempenich/Appdaemon-Test-Framework#32]
## Context
A bug found by @chbndrhnns was present when using `appdaemon` version `4.0.0` or later. A fix was quickly introduced. But @lifeisafractal raised the question:
**Should we be supporting Appdaemon v3 and v4? or only the latest (v4)?**

Let's use this issue to discuss the pros and cons and decide how to move forward.

**Comment by sj3fk3** [comment]
I would argue that anyone savvy enough to use this test-framework will also be on v4. I honestly see no reason why you would want to stay on v3 even if "it just works".

**Comment by FlorianKempenich** [comment]
Hi @sj3fk3 ,

Thanks for your input on that issue. I tend to think the same, as in: If you know how to update one dependency (`appdaemon`), then you should be able to figure out how to update another one as well (`appdaemontestframework`)

The reason I was considering the support for both versions for a while (with gradual deprecation), was to avoid a situation where you just build your project that has always worked and then, out of nowhere you get an error and you have no idea why.

**Comment by lifeisafractal** [comment]
I think I agree with @sj3fk3 as well. Generally people who are using TDD on their `appdaemon` framework will likely be on the most recent version of `appdaemon`. Also, if they are following good practice and have both `appdaemon` and `appdaemontestframework` pinned in their requirements, they should only break when explicitly updating one or the other.

**Comment by lifeisafractal** [comment]
One more thought that came after hitting send, I would consider the first release of `appdaemontestframework` that only supports 4.x of `appdaemon` to be a breaking change, and it feels like a major version bump might be in order to communicate that to people. That would help with the 'out of nowhere error` issue.

**Comment by FlorianKempenich** [comment]
Thanks for your inputs @sj3fk3 and @lifeisafractal .
I think we all agree, so let's proceed this way:
- In the current MAJOR version, I'll add a warning if `appdaemon` version 3 or below is being used, and release as a minor version
- In the next MAJOR version, the warning will be transformed into an error and only the latest version will be supported.

All good with everyone? 🙂
