### ISSUE TITLE
Test setup should cover all supported Python versions

### ISSUE THREAD

**Issue by lifeisafractal** [FlorianKempenich/Appdaemon-Test-Framework#38]
Currently the Tox tests are only run against Python 3.6. #37 and #36 both show Python 3.8 issues that could be cause with automated test coverage.

Proposal:
* We create a policy of what Python versions are supported. I suggest we follow upstream HomeAssistant policy of [supporting the 2 most recent minor stable releases](https://github.com/home-assistant/architecture/blob/master/adr/0002-minimum-supported-python-version.md).
* Extend Tox coverage to test with both these supported versions both for local testing and for the automated testing

Immediate consequences:
* Python 3.6 would be deprecated and heading for removal in the next couple releases.

**Comment by FlorianKempenich** [comment]
Yes. I agree. Let's support 3.7 & 3.8 (and update tox)

For now, there's still a bug with 3.8, #37 is fixing it but I'd like to spend some time to understand _how_ it's fixing it before merging.
I'll probably have some time to look at that on Monday
