### ISSUE TITLE
The latest (4.0.0b1) distribution is missing files

### ISSUE THREAD

**Issue by fhoekstra** [FlorianKempenich/Appdaemon-Test-Framework#57]
Apparently I was wrong and the wildcard was needed. 🤦‍♂️

**Comment by FlorianKempenich** [comment]
No worries. How can we test this locally? (without pushing a new version to pypi)

**Comment by FlorianKempenich** [comment]
Also, I realized that I forgot to update 
```
python_requires=">=3.6",
```
when dropping support for python 3.6. We might want to use the opportunity to fix that as well.

**Comment by fhoekstra** [comment]
See #58 
I built the wheel locally, then installed it into my working environment and re-ran

**Comment by fhoekstra** [comment]
And yes, I realized the same when I looked at that file 😄

**Comment by FlorianKempenich** [comment]
Haha. I've just seen your PR. You already fixed the point I mentioned above 😁👍

>  I built the wheel locally, then installed it into my working environment and re-ran

Could you write down the steps to do this? (I haven't worked with python in a year or so 😅)
I'd like to check it out as well

**Comment by fhoekstra** [comment]
Sure, in your local folder with this repo, you build the wheel using:
`python setup.py bdist_wheel`

Then you get a file on this path: `dist/appdaemontestframework-4.0.0b2-py3-none-any.whl`

That file can be installed into the venv you use for running your own appdaemon tests by running the following command from that venv:
`python -m pip install <path_to_wheel>`
I typically drag and drop the wheel to my prod appdaemon env because it simplifies the last command

**Comment by FlorianKempenich** [comment]
Cool. Thanks for the info, very useful for when I'll give that a go 😃 But for now I decided to trust you and I merged #58. So I'm closing this
